name: setor_dados
channels:
  - defaults          # sรณ o canal oficial
channel_priority: strict
auto_update_conda: false
allow_conda_downgrades: false
always_yes: true      # suprime perguntas interativas

